#  Copyright 2022-present, the Waterdip Labs Pvt. Ltd.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

METRICS_MODEL_ID = "de5af49c-e70b-4852-b8dd-3b8fdd7f98f8"
METRICS_MODEL_VERSION_ID_V1 = "de5af49c-e61e-4752-b8dd-3b8fdd7f98f8"
METRICS_MODEL_VERSION_ID_V1_NAME = "v1"
METRICS_DATASET_EVENT_ID_V1 = "de4af49a-e61e-7750-b8cd-3b8fdd7f98f8"
METRICS_DATASET_BATCH_ID_V1_1 = "de4af49a-e61e-8752-b8dd-3b8fdd7f98f8"
METRICS_MODEL_VERSION_V1_SCHEMA = {
    "features": {
        "cap-shape": {"data_type": "CATEGORICAL", "list_index": 0},
        "cap-surface": {"data_type": "CATEGORICAL", "list_index": 1},
        "cap-color": {"data_type": "CATEGORICAL", "list_index": 2},
        "bruises": {"data_type": "CATEGORICAL", "list_index": 3},
        "length": {"data_type": "NUMERIC", "list_index": 4},
        "height": {"data_type": "NUMERIC", "list_index": 5},
    },
    "predictions": {"class": {"data_type": "CATEGORICAL", "list_index": 0}},
}

metrics_batch_data_rows = [
    [
        {
            "name": "class",
            "value_categorical": "e",
            "data_type": "CATEGORICAL",
            "mapping_type": "PREDICTION",
        },
        {
            "name": "cap-shape",
            "value_categorical": "f",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "cap-surface",
            "value_categorical": "y",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "cap-color",
            "value_categorical": "y",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "bruises",
            "value_categorical": "t",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "length",
            "value_numeric": 71,
            "data_type": "NUMERIC",
            "mapping_type": "FEATURE",
        },
        {
            "name": "height",
            "value_numeric": 45,
            "data_type": "NUMERIC",
            "mapping_type": "FEATURE",
        },
    ],
    [
        {
            "name": "class",
            "value_categorical": "p",
            "data_type": "CATEGORICAL",
            "mapping_type": "PREDICTION",
        },
        {
            "name": "cap-shape",
            "value_categorical": "x",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "cap-surface",
            "value_categorical": "f",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "cap-color",
            "value_categorical": "g",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "bruises",
            "value_categorical": "f",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "length",
            "value_numeric": 18,
            "data_type": "NUMERIC",
            "mapping_type": "FEATURE",
        },
        {
            "name": "height",
            "value_numeric": 78,
            "data_type": "NUMERIC",
            "mapping_type": "FEATURE",
        },
    ],
    [
        {
            "name": "class",
            "value_categorical": "e",
            "data_type": "CATEGORICAL",
            "mapping_type": "PREDICTION",
        },
        {
            "name": "cap-shape",
            "value_categorical": "x",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "cap-surface",
            "value_categorical": "s",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "cap-color",
            "value_categorical": "w",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "bruises",
            "value_categorical": "f",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "length",
            "value_numeric": 77,
            "data_type": "NUMERIC",
            "mapping_type": "FEATURE",
        },
        {
            "name": "height",
            "value_numeric": 87,
            "data_type": "NUMERIC",
            "mapping_type": "FEATURE",
        },
    ],
    [
        {
            "name": "class",
            "value_categorical": "p",
            "data_type": "CATEGORICAL",
            "mapping_type": "PREDICTION",
        },
        {
            "name": "cap-shape",
            "value_categorical": "f",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "cap-surface",
            "value_categorical": "y",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "cap-color",
            "value_categorical": "n",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "bruises",
            "value_categorical": "f",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "length",
            "value_numeric": 7,
            "data_type": "NUMERIC",
            "mapping_type": "FEATURE",
        },
        {
            "name": "height",
            "value_numeric": 76,
            "data_type": "NUMERIC",
            "mapping_type": "FEATURE",
        },
    ],
    [
        {
            "name": "class",
            "value_categorical": "e",
            "data_type": "CATEGORICAL",
            "mapping_type": "PREDICTION",
        },
        {
            "name": "cap-shape",
            "value_categorical": "x",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "cap-surface",
            "value_categorical": "f",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "cap-color",
            "value_categorical": "g",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "bruises",
            "value_categorical": "f",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "length",
            "value_numeric": 69,
            "data_type": "NUMERIC",
            "mapping_type": "FEATURE",
        },
        {
            "name": "height",
            "value_numeric": 39,
            "data_type": "NUMERIC",
            "mapping_type": "FEATURE",
        },
    ],
    [
        {
            "name": "class",
            "value_categorical": "e",
            "data_type": "CATEGORICAL",
            "mapping_type": "PREDICTION",
        },
        {
            "name": "cap-shape",
            "value_categorical": "f",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "cap-surface",
            "value_categorical": "y",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "cap-color",
            "value_categorical": "e",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "bruises",
            "value_categorical": "t",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "length",
            "value_numeric": 72,
            "data_type": "NUMERIC",
            "mapping_type": "FEATURE",
        },
        {
            "name": "height",
            "value_numeric": 4,
            "data_type": "NUMERIC",
            "mapping_type": "FEATURE",
        },
    ],
    [
        {
            "name": "class",
            "value_categorical": "e",
            "data_type": "CATEGORICAL",
            "mapping_type": "PREDICTION",
        },
        {
            "name": "cap-shape",
            "value_categorical": "b",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "cap-surface",
            "value_categorical": "y",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "cap-color",
            "value_categorical": "n",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "bruises",
            "value_categorical": "f",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "length",
            "value_numeric": 86,
            "data_type": "NUMERIC",
            "mapping_type": "FEATURE",
        },
        {
            "name": "height",
            "value_numeric": 58,
            "data_type": "NUMERIC",
            "mapping_type": "FEATURE",
        },
    ],
    [
        {
            "name": "class",
            "value_categorical": "e",
            "data_type": "CATEGORICAL",
            "mapping_type": "PREDICTION",
        },
        {
            "name": "cap-shape",
            "value_categorical": "x",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "cap-surface",
            "value_categorical": "y",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "cap-color",
            "value_categorical": "e",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "bruises",
            "value_categorical": "t",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "length",
            "value_numeric": 84,
            "data_type": "NUMERIC",
            "mapping_type": "FEATURE",
        },
        {
            "name": "height",
            "value_numeric": 1,
            "data_type": "NUMERIC",
            "mapping_type": "FEATURE",
        },
    ],
    [
        {
            "name": "class",
            "value_categorical": "e",
            "data_type": "CATEGORICAL",
            "mapping_type": "PREDICTION",
        },
        {
            "name": "cap-shape",
            "value_categorical": "s",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "cap-surface",
            "value_categorical": "f",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "cap-color",
            "value_categorical": "g",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "bruises",
            "value_categorical": "f",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "length",
            "value_numeric": 38,
            "data_type": "NUMERIC",
            "mapping_type": "FEATURE",
        },
        {
            "name": "height",
            "value_numeric": 35,
            "data_type": "NUMERIC",
            "mapping_type": "FEATURE",
        },
    ],
    [
        {
            "name": "class",
            "value_categorical": "e",
            "data_type": "CATEGORICAL",
            "mapping_type": "PREDICTION",
        },
        {
            "name": "cap-shape",
            "value_categorical": "x",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "cap-surface",
            "value_categorical": "f",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "cap-color",
            "value_categorical": "n",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "bruises",
            "value_categorical": "t",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "length",
            "value_numeric": 6,
            "data_type": "NUMERIC",
            "mapping_type": "FEATURE",
        },
        {
            "name": "height",
            "value_numeric": 24,
            "data_type": "NUMERIC",
            "mapping_type": "FEATURE",
        },
    ],
    [
        {
            "name": "class",
            "value_categorical": "e",
            "data_type": "CATEGORICAL",
            "mapping_type": "PREDICTION",
        },
        {
            "name": "cap-shape",
            "value_categorical": "x",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "cap-surface",
            "value_categorical": "y",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "cap-color",
            "value_categorical": "n",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "bruises",
            "value_categorical": "t",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "length",
            "value_numeric": 90,
            "data_type": "NUMERIC",
            "mapping_type": "FEATURE",
        },
        {
            "name": "height",
            "value_numeric": 90,
            "data_type": "NUMERIC",
            "mapping_type": "FEATURE",
        },
    ],
    [
        {
            "name": "class",
            "value_categorical": "e",
            "data_type": "CATEGORICAL",
            "mapping_type": "PREDICTION",
        },
        {
            "name": "cap-shape",
            "value_categorical": "x",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "cap-surface",
            "value_categorical": "s",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "cap-color",
            "value_categorical": "y",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "bruises",
            "value_categorical": "t",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "length",
            "value_numeric": 16,
            "data_type": "NUMERIC",
            "mapping_type": "FEATURE",
        },
        {
            "name": "height",
            "value_numeric": 95,
            "data_type": "NUMERIC",
            "mapping_type": "FEATURE",
        },
    ],
    [
        {
            "name": "class",
            "value_categorical": "p",
            "data_type": "CATEGORICAL",
            "mapping_type": "PREDICTION",
        },
        {
            "name": "cap-shape",
            "value_categorical": "f",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "cap-surface",
            "value_categorical": "f",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "cap-color",
            "value_categorical": "y",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "bruises",
            "value_categorical": "f",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "length",
            "value_numeric": 83,
            "data_type": "NUMERIC",
            "mapping_type": "FEATURE",
        },
        {
            "name": "height",
            "value_numeric": 93,
            "data_type": "NUMERIC",
            "mapping_type": "FEATURE",
        },
    ],
    [
        {
            "name": "class",
            "value_categorical": "e",
            "data_type": "CATEGORICAL",
            "mapping_type": "PREDICTION",
        },
        {
            "name": "cap-shape",
            "value_categorical": "x",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "cap-surface",
            "value_categorical": "f",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "cap-color",
            "value_categorical": "w",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "bruises",
            "value_categorical": "f",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "length",
            "value_numeric": 97,
            "data_type": "NUMERIC",
            "mapping_type": "FEATURE",
        },
        {
            "name": "height",
            "value_numeric": 15,
            "data_type": "NUMERIC",
            "mapping_type": "FEATURE",
        },
    ],
    [
        {
            "name": "class",
            "value_categorical": "p",
            "data_type": "CATEGORICAL",
            "mapping_type": "PREDICTION",
        },
        {
            "name": "cap-shape",
            "value_categorical": "f",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "cap-surface",
            "value_categorical": "f",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "cap-color",
            "value_categorical": "g",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "bruises",
            "value_categorical": "f",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "length",
            "value_numeric": 58,
            "data_type": "NUMERIC",
            "mapping_type": "FEATURE",
        },
        {
            "name": "height",
            "value_numeric": 2,
            "data_type": "NUMERIC",
            "mapping_type": "FEATURE",
        },
    ],
    [
        {
            "name": "class",
            "value_categorical": "p",
            "data_type": "CATEGORICAL",
            "mapping_type": "PREDICTION",
        },
        {
            "name": "cap-shape",
            "value_categorical": "f",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "cap-surface",
            "value_categorical": "s",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "cap-color",
            "value_categorical": "n",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "bruises",
            "value_categorical": "f",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "length",
            "value_numeric": 18,
            "data_type": "NUMERIC",
            "mapping_type": "FEATURE",
        },
        {
            "name": "height",
            "value_numeric": 32,
            "data_type": "NUMERIC",
            "mapping_type": "FEATURE",
        },
    ],
    [
        {
            "name": "class",
            "value_categorical": "e",
            "data_type": "CATEGORICAL",
            "mapping_type": "PREDICTION",
        },
        {
            "name": "cap-shape",
            "value_categorical": "x",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "cap-surface",
            "value_categorical": "f",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "cap-color",
            "value_categorical": "g",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "bruises",
            "value_categorical": "t",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "length",
            "value_numeric": 9,
            "data_type": "NUMERIC",
            "mapping_type": "FEATURE",
        },
        {
            "name": "height",
            "value_numeric": 97,
            "data_type": "NUMERIC",
            "mapping_type": "FEATURE",
        },
    ],
    [
        {
            "name": "class",
            "value_categorical": "e",
            "data_type": "CATEGORICAL",
            "mapping_type": "PREDICTION",
        },
        {
            "name": "cap-shape",
            "value_categorical": "x",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "cap-surface",
            "value_categorical": "y",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "cap-color",
            "value_categorical": "e",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "bruises",
            "value_categorical": "t",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "length",
            "value_numeric": 21,
            "data_type": "NUMERIC",
            "mapping_type": "FEATURE",
        },
        {
            "name": "height",
            "value_numeric": 67,
            "data_type": "NUMERIC",
            "mapping_type": "FEATURE",
        },
    ],
    [
        {
            "name": "class",
            "value_categorical": "e",
            "data_type": "CATEGORICAL",
            "mapping_type": "PREDICTION",
        },
        {
            "name": "cap-shape",
            "value_categorical": "x",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "cap-surface",
            "value_categorical": "y",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "cap-color",
            "value_categorical": "e",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "bruises",
            "value_categorical": "t",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "length",
            "value_numeric": 98,
            "data_type": "NUMERIC",
            "mapping_type": "FEATURE",
        },
        {
            "name": "height",
            "value_numeric": 72,
            "data_type": "NUMERIC",
            "mapping_type": "FEATURE",
        },
    ],
    [
        {
            "name": "class",
            "value_categorical": "e",
            "data_type": "CATEGORICAL",
            "mapping_type": "PREDICTION",
        },
        {
            "name": "cap-shape",
            "value_categorical": "x",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "cap-surface",
            "value_categorical": "y",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "cap-color",
            "value_categorical": "g",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "bruises",
            "value_categorical": "t",
            "data_type": "CATEGORICAL",
            "mapping_type": "FEATURE",
        },
        {
            "name": "length",
            "value_numeric": 62,
            "data_type": "NUMERIC",
            "mapping_type": "FEATURE",
        },
        {
            "name": "height",
            "value_numeric": 28,
            "data_type": "NUMERIC",
            "mapping_type": "FEATURE",
        },
    ],
]

metrics_event_rows = [
    {
        "columns": [
            {
                "name": "class",
                "value_categorical": "p",
                "data_type": "CATEGORICAL",
                "mapping_type": "PREDICTION",
            },
            {
                "name": "cap-shape",
                "value_categorical": "x",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-surface",
                "value_categorical": "y",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-color",
                "value_categorical": "n",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "bruises",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "length",
                "value_numeric": 8,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
            {
                "name": "height",
                "value_numeric": 97,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
        ],
        "created_at": "2022-12-21T00:00:00",
    },
    {
        "columns": [
            {
                "name": "class",
                "value_categorical": "e",
                "data_type": "CATEGORICAL",
                "mapping_type": "PREDICTION",
            },
            {
                "name": "cap-shape",
                "value_categorical": "k",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-surface",
                "value_categorical": "s",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-color",
                "value_categorical": "b",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "bruises",
                "value_categorical": "t",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "length",
                "value_numeric": 28,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
            {
                "name": "height",
                "value_numeric": 51,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
        ],
        "created_at": "2022-12-23T00:00:00",
    },
    {
        "columns": [
            {
                "name": "class",
                "value_categorical": "e",
                "data_type": "CATEGORICAL",
                "mapping_type": "PREDICTION",
            },
            {
                "name": "cap-shape",
                "value_categorical": "x",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-surface",
                "value_categorical": "y",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-color",
                "value_categorical": "w",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "bruises",
                "value_categorical": "t",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "length",
                "value_numeric": 11,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
            {
                "name": "height",
                "value_numeric": 74,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
        ],
        "created_at": "2022-12-25T00:00:00",
    },
    {
        "columns": [
            {
                "name": "class",
                "value_categorical": "e",
                "data_type": "CATEGORICAL",
                "mapping_type": "PREDICTION",
            },
            {
                "name": "cap-shape",
                "value_categorical": "x",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-surface",
                "value_categorical": "s",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-color",
                "value_categorical": "w",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "bruises",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "length",
                "value_numeric": 81,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
            {
                "name": "height",
                "value_numeric": 89,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
        ],
        "created_at": "2022-12-14T00:00:00",
    },
    {
        "columns": [
            {
                "name": "class",
                "value_categorical": "e",
                "data_type": "CATEGORICAL",
                "mapping_type": "PREDICTION",
            },
            {
                "name": "cap-shape",
                "value_categorical": "x",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-surface",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-color",
                "value_categorical": "w",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "bruises",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "length",
                "value_numeric": 33,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
            {
                "name": "height",
                "value_numeric": 25,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
        ],
        "created_at": "2022-12-12T00:00:00",
    },
    {
        "columns": [
            {
                "name": "class",
                "value_categorical": "p",
                "data_type": "CATEGORICAL",
                "mapping_type": "PREDICTION",
            },
            {
                "name": "cap-shape",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-surface",
                "value_categorical": "y",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-color",
                "value_categorical": "y",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "bruises",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "length",
                "value_numeric": 67,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
            {
                "name": "height",
                "value_numeric": 82,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
        ],
        "created_at": "2022-12-20T00:00:00",
    },
    {
        "columns": [
            {
                "name": "class",
                "value_categorical": "p",
                "data_type": "CATEGORICAL",
                "mapping_type": "PREDICTION",
            },
            {
                "name": "cap-shape",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-surface",
                "value_categorical": "y",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-color",
                "value_categorical": "w",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "bruises",
                "value_categorical": "t",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "length",
                "value_numeric": 93,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
            {
                "name": "height",
                "value_numeric": 3,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
        ],
        "created_at": "2022-12-06T00:00:00",
    },
    {
        "columns": [
            {
                "name": "class",
                "value_categorical": "e",
                "data_type": "CATEGORICAL",
                "mapping_type": "PREDICTION",
            },
            {
                "name": "cap-shape",
                "value_categorical": "x",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-surface",
                "value_categorical": "y",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-color",
                "value_categorical": "g",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "bruises",
                "value_categorical": "t",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "length",
                "value_numeric": 82,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
            {
                "name": "height",
                "value_numeric": 77,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
        ],
        "created_at": "2022-12-30T00:00:00",
    },
    {
        "columns": [
            {
                "name": "class",
                "value_categorical": "p",
                "data_type": "CATEGORICAL",
                "mapping_type": "PREDICTION",
            },
            {
                "name": "cap-shape",
                "value_categorical": "x",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-surface",
                "value_categorical": "s",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-color",
                "value_categorical": "p",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "bruises",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "length",
                "value_numeric": 38,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
            {
                "name": "height",
                "value_numeric": 56,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
        ],
        "created_at": "2022-12-07T00:00:00",
    },
    {
        "columns": [
            {
                "name": "class",
                "value_categorical": "e",
                "data_type": "CATEGORICAL",
                "mapping_type": "PREDICTION",
            },
            {
                "name": "cap-shape",
                "value_categorical": "k",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-surface",
                "value_categorical": "y",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-color",
                "value_categorical": "n",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "bruises",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "length",
                "value_numeric": 7,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
            {
                "name": "height",
                "value_numeric": 44,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
        ],
        "created_at": "2022-12-03T00:00:00",
    },
    {
        "columns": [
            {
                "name": "class",
                "value_categorical": "e",
                "data_type": "CATEGORICAL",
                "mapping_type": "PREDICTION",
            },
            {
                "name": "cap-shape",
                "value_categorical": "x",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-surface",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-color",
                "value_categorical": "e",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "bruises",
                "value_categorical": "t",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "length",
                "value_numeric": 97,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
            {
                "name": "height",
                "value_numeric": 73,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
        ],
        "created_at": "2022-12-03T00:00:00",
    },
    {
        "columns": [
            {
                "name": "class",
                "value_categorical": "e",
                "data_type": "CATEGORICAL",
                "mapping_type": "PREDICTION",
            },
            {
                "name": "cap-shape",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-surface",
                "value_categorical": "s",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-color",
                "value_categorical": "w",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "bruises",
                "value_categorical": "t",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "length",
                "value_numeric": 44,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
            {
                "name": "height",
                "value_numeric": 33,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
        ],
        "created_at": "2022-12-15T00:00:00",
    },
    {
        "columns": [
            {
                "name": "class",
                "value_categorical": "p",
                "data_type": "CATEGORICAL",
                "mapping_type": "PREDICTION",
            },
            {
                "name": "cap-shape",
                "value_categorical": "x",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-surface",
                "value_categorical": "s",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-color",
                "value_categorical": "b",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "bruises",
                "value_categorical": "t",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "length",
                "value_numeric": 10,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
            {
                "name": "height",
                "value_numeric": 87,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
        ],
        "created_at": "2022-12-04T00:00:00",
    },
    {
        "columns": [
            {
                "name": "class",
                "value_categorical": "e",
                "data_type": "CATEGORICAL",
                "mapping_type": "PREDICTION",
            },
            {
                "name": "cap-shape",
                "value_categorical": "b",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-surface",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-color",
                "value_categorical": "w",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "bruises",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "length",
                "value_numeric": 87,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
            {
                "name": "height",
                "value_numeric": 80,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
        ],
        "created_at": "2022-12-04T00:00:00",
    },
    {
        "columns": [
            {
                "name": "class",
                "value_categorical": "p",
                "data_type": "CATEGORICAL",
                "mapping_type": "PREDICTION",
            },
            {
                "name": "cap-shape",
                "value_categorical": "x",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-surface",
                "value_categorical": "s",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-color",
                "value_categorical": "e",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "bruises",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "length",
                "value_numeric": 78,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
            {
                "name": "height",
                "value_numeric": 52,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
        ],
        "created_at": "2022-12-15T00:00:00",
    },
    {
        "columns": [
            {
                "name": "class",
                "value_categorical": "p",
                "data_type": "CATEGORICAL",
                "mapping_type": "PREDICTION",
            },
            {
                "name": "cap-shape",
                "value_categorical": "x",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-surface",
                "value_categorical": "y",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-color",
                "value_categorical": "g",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "bruises",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "length",
                "value_numeric": 31,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
            {
                "name": "height",
                "value_numeric": 41,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
        ],
        "created_at": "2022-12-17T00:00:00",
    },
    {
        "columns": [
            {
                "name": "class",
                "value_categorical": "p",
                "data_type": "CATEGORICAL",
                "mapping_type": "PREDICTION",
            },
            {
                "name": "cap-shape",
                "value_categorical": "x",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-surface",
                "value_categorical": "s",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-color",
                "value_categorical": "e",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "bruises",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "length",
                "value_numeric": 58,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
            {
                "name": "height",
                "value_numeric": 83,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
        ],
        "created_at": "2022-12-26T00:00:00",
    },
    {
        "columns": [
            {
                "name": "class",
                "value_categorical": "p",
                "data_type": "CATEGORICAL",
                "mapping_type": "PREDICTION",
            },
            {
                "name": "cap-shape",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-surface",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-color",
                "value_categorical": "g",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "bruises",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "length",
                "value_numeric": 81,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
            {
                "name": "height",
                "value_numeric": 76,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
        ],
        "created_at": "2022-12-30T00:00:00",
    },
    {
        "columns": [
            {
                "name": "class",
                "value_categorical": "p",
                "data_type": "CATEGORICAL",
                "mapping_type": "PREDICTION",
            },
            {
                "name": "cap-shape",
                "value_categorical": "x",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-surface",
                "value_categorical": "y",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-color",
                "value_categorical": "w",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "bruises",
                "value_categorical": "t",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "length",
                "value_numeric": 80,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
            {
                "name": "height",
                "value_numeric": 26,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
        ],
        "created_at": "2022-12-29T00:00:00",
    },
    {
        "columns": [
            {
                "name": "class",
                "value_categorical": "p",
                "data_type": "CATEGORICAL",
                "mapping_type": "PREDICTION",
            },
            {
                "name": "cap-shape",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-surface",
                "value_categorical": "y",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-color",
                "value_categorical": "g",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "bruises",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "length",
                "value_numeric": 5,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
            {
                "name": "height",
                "value_numeric": 18,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
        ],
        "created_at": "2022-12-20T00:00:00",
    },
    {
        "columns": [
            {
                "name": "class",
                "value_categorical": "e",
                "data_type": "CATEGORICAL",
                "mapping_type": "PREDICTION",
            },
            {
                "name": "cap-shape",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-surface",
                "value_categorical": "y",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-color",
                "value_categorical": "n",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "bruises",
                "value_categorical": "t",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "length",
                "value_numeric": 97,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
            {
                "name": "height",
                "value_numeric": 32,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
        ],
        "created_at": "2022-12-13T00:00:00",
    },
    {
        "columns": [
            {
                "name": "class",
                "value_categorical": "e",
                "data_type": "CATEGORICAL",
                "mapping_type": "PREDICTION",
            },
            {
                "name": "cap-shape",
                "value_categorical": "x",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-surface",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-color",
                "value_categorical": "n",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "bruises",
                "value_categorical": "t",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "length",
                "value_numeric": 42,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
            {
                "name": "height",
                "value_numeric": 21,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
        ],
        "created_at": "2022-12-28T00:00:00",
    },
    {
        "columns": [
            {
                "name": "class",
                "value_categorical": "e",
                "data_type": "CATEGORICAL",
                "mapping_type": "PREDICTION",
            },
            {
                "name": "cap-shape",
                "value_categorical": "x",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-surface",
                "value_categorical": "y",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-color",
                "value_categorical": "g",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "bruises",
                "value_categorical": "t",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "length",
                "value_numeric": 4,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
            {
                "name": "height",
                "value_numeric": 24,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
        ],
        "created_at": "2022-12-09T00:00:00",
    },
    {
        "columns": [
            {
                "name": "class",
                "value_categorical": "p",
                "data_type": "CATEGORICAL",
                "mapping_type": "PREDICTION",
            },
            {
                "name": "cap-shape",
                "value_categorical": "x",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-surface",
                "value_categorical": "s",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-color",
                "value_categorical": "w",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "bruises",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "length",
                "value_numeric": 37,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
            {
                "name": "height",
                "value_numeric": 48,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
        ],
        "created_at": "2022-12-08T00:00:00",
    },
    {
        "columns": [
            {
                "name": "class",
                "value_categorical": "p",
                "data_type": "CATEGORICAL",
                "mapping_type": "PREDICTION",
            },
            {
                "name": "cap-shape",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-surface",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-color",
                "value_categorical": "y",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "bruises",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "length",
                "value_numeric": 58,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
            {
                "name": "height",
                "value_numeric": 93,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
        ],
        "created_at": "2022-12-02T00:00:00",
    },
    {
        "columns": [
            {
                "name": "class",
                "value_categorical": "e",
                "data_type": "CATEGORICAL",
                "mapping_type": "PREDICTION",
            },
            {
                "name": "cap-shape",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-surface",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-color",
                "value_categorical": "e",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "bruises",
                "value_categorical": "t",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "length",
                "value_numeric": 15,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
            {
                "name": "height",
                "value_numeric": 58,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
        ],
        "created_at": "2022-12-20T00:00:00",
    },
    {
        "columns": [
            {
                "name": "class",
                "value_categorical": "p",
                "data_type": "CATEGORICAL",
                "mapping_type": "PREDICTION",
            },
            {
                "name": "cap-shape",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-surface",
                "value_categorical": "y",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-color",
                "value_categorical": "n",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "bruises",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "length",
                "value_numeric": 59,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
            {
                "name": "height",
                "value_numeric": 72,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
        ],
        "created_at": "2022-12-30T00:00:00",
    },
    {
        "columns": [
            {
                "name": "class",
                "value_categorical": "e",
                "data_type": "CATEGORICAL",
                "mapping_type": "PREDICTION",
            },
            {
                "name": "cap-shape",
                "value_categorical": "x",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-surface",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-color",
                "value_categorical": "g",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "bruises",
                "value_categorical": "t",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "length",
                "value_numeric": 80,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
            {
                "name": "height",
                "value_numeric": 70,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
        ],
        "created_at": "2022-12-02T00:00:00",
    },
    {
        "columns": [
            {
                "name": "class",
                "value_categorical": "p",
                "data_type": "CATEGORICAL",
                "mapping_type": "PREDICTION",
            },
            {
                "name": "cap-shape",
                "value_categorical": "x",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-surface",
                "value_categorical": "s",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-color",
                "value_categorical": "e",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "bruises",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "length",
                "value_numeric": 84,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
            {
                "name": "height",
                "value_numeric": 7,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
        ],
        "created_at": "2022-12-01T00:00:00",
    },
    {
        "columns": [
            {
                "name": "class",
                "value_categorical": "e",
                "data_type": "CATEGORICAL",
                "mapping_type": "PREDICTION",
            },
            {
                "name": "cap-shape",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-surface",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-color",
                "value_categorical": "n",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "bruises",
                "value_categorical": "t",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "length",
                "value_numeric": 1,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
            {
                "name": "height",
                "value_numeric": 7,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
        ],
        "created_at": "2022-12-27T00:00:00",
    },
    {
        "columns": [
            {
                "name": "class",
                "value_categorical": "e",
                "data_type": "CATEGORICAL",
                "mapping_type": "PREDICTION",
            },
            {
                "name": "cap-shape",
                "value_categorical": "x",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-surface",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-color",
                "value_categorical": "w",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "bruises",
                "value_categorical": "t",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "length",
                "value_numeric": 70,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
            {
                "name": "height",
                "value_numeric": 86,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
        ],
        "created_at": "2022-12-18T00:00:00",
    },
    {
        "columns": [
            {
                "name": "class",
                "value_categorical": "p",
                "data_type": "CATEGORICAL",
                "mapping_type": "PREDICTION",
            },
            {
                "name": "cap-shape",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-surface",
                "value_categorical": "y",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-color",
                "value_categorical": "y",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "bruises",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "length",
                "value_numeric": 78,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
            {
                "name": "height",
                "value_numeric": 97,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
        ],
        "created_at": "2022-12-11T00:00:00",
    },
    {
        "columns": [
            {
                "name": "class",
                "value_categorical": "p",
                "data_type": "CATEGORICAL",
                "mapping_type": "PREDICTION",
            },
            {
                "name": "cap-shape",
                "value_categorical": "x",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-surface",
                "value_categorical": "y",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-color",
                "value_categorical": "g",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "bruises",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "length",
                "value_numeric": 52,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
            {
                "name": "height",
                "value_numeric": 77,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
        ],
        "created_at": "2022-12-08T00:00:00",
    },
    {
        "columns": [
            {
                "name": "class",
                "value_categorical": "p",
                "data_type": "CATEGORICAL",
                "mapping_type": "PREDICTION",
            },
            {
                "name": "cap-shape",
                "value_categorical": "x",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-surface",
                "value_categorical": "y",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-color",
                "value_categorical": "e",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "bruises",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "length",
                "value_numeric": 34,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
            {
                "name": "height",
                "value_numeric": 47,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
        ],
        "created_at": "2022-12-05T00:00:00",
    },
    {
        "columns": [
            {
                "name": "class",
                "value_categorical": "e",
                "data_type": "CATEGORICAL",
                "mapping_type": "PREDICTION",
            },
            {
                "name": "cap-shape",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-surface",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-color",
                "value_categorical": "n",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "bruises",
                "value_categorical": "t",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "length",
                "value_numeric": 90,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
            {
                "name": "height",
                "value_numeric": 25,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
        ],
        "created_at": "2022-12-01T00:00:00",
    },
    {
        "columns": [
            {
                "name": "class",
                "value_categorical": "e",
                "data_type": "CATEGORICAL",
                "mapping_type": "PREDICTION",
            },
            {
                "name": "cap-shape",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-surface",
                "value_categorical": "s",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-color",
                "value_categorical": "g",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "bruises",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "length",
                "value_numeric": 17,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
            {
                "name": "height",
                "value_numeric": 43,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
        ],
        "created_at": "2022-12-09T00:00:00",
    },
    {
        "columns": [
            {
                "name": "class",
                "value_categorical": "p",
                "data_type": "CATEGORICAL",
                "mapping_type": "PREDICTION",
            },
            {
                "name": "cap-shape",
                "value_categorical": "x",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-surface",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-color",
                "value_categorical": "y",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "bruises",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "length",
                "value_numeric": 65,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
            {
                "name": "height",
                "value_numeric": 85,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
        ],
        "created_at": "2022-12-07T00:00:00",
    },
    {
        "columns": [
            {
                "name": "class",
                "value_categorical": "e",
                "data_type": "CATEGORICAL",
                "mapping_type": "PREDICTION",
            },
            {
                "name": "cap-shape",
                "value_categorical": "x",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-surface",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-color",
                "value_categorical": "g",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "bruises",
                "value_categorical": "t",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "length",
                "value_numeric": 92,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
            {
                "name": "height",
                "value_numeric": 82,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
        ],
        "created_at": "2022-12-10T00:00:00",
    },
    {
        "columns": [
            {
                "name": "class",
                "value_categorical": "e",
                "data_type": "CATEGORICAL",
                "mapping_type": "PREDICTION",
            },
            {
                "name": "cap-shape",
                "value_categorical": "x",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-surface",
                "value_categorical": "f",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "cap-color",
                "value_categorical": "g",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "bruises",
                "value_categorical": "t",
                "data_type": "CATEGORICAL",
                "mapping_type": "FEATURE",
            },
            {
                "name": "length",
                "value_numeric": 81,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
            {
                "name": "height",
                "value_numeric": 90,
                "data_type": "NUMERIC",
                "mapping_type": "FEATURE",
            },
        ],
        "created_at": "2022-12-28T00:00:00",
    },
]
